'use client';  // Оставляем директиву для клиентского компонента

import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";  // Импортируем Head для добавления мета-тегов

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>  {/* Указываем заголовок страницы прямо в Head */}
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}